### ISSUE TITLE
tests (node 7.7.1)

### ISSUE THREAD

**Issue by mckennatim** [Cosecha/redadalertas-api#18]
The following leaks were detected:__core-js_shared__
npm ERR! Test failed.  See above for more details.

Seems to be an issue for some versions of node. In Lab issues it is suggested to add --leaks to the test invocation

`    "test": "lab -T node_modules/lab-babel test --leaks",`

Also 
`lab.test('It requires verified',`... is failing to find `expect(err.errors.verified).to.exist;`. Replacing that with `expect(err.errors.type.message).to.exist;` fixes that test. 

Should I do a pull request?

**Comment by celsom3** [comment]
Yes, please. I haven't learned to use Lab for testing. Someone else set that up, so I'm a bit clueless. May revert to using Mocha/Chai later though...
